apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-volume
  labels:
    type: local
spec:
  storageClassName: nfs-client
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.35  # NFS 서버의 IP 주소
    path: "/str"          # NFS 서버의 공유 경로