apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: k8s
    tier: backend
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    nodePort: 31002
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s
      tier: backend
  template:
    metadata:
      labels:
        app: k8s
        tier: backend
    spec:
      containers:
      - name: k8s
        image: joyoungkyung/k8s_backend:1.0
        ports:
        - containerPort: 8000
